# Generated by Django 3.0.6 on 2020-06-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_files_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
